[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "tc_sqd"
version = "0.1.0"
description = "Sample-based Quantum Diagonalization (SQD) for TensorCircuit"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "tensorcircuit==0.12.0",
    "numpy>=1.17,<2.0",
    "scipy>=1.10,<1.14",
    "pyscf>=2.0",
]

[tool.setuptools.packages.find]
where = ["src"]
